variables:
  GIT_SSL_NO_VERIFY: '1'

stages:
  - build
  - test

assemble_job: # Assembles the project without generating anything
  stage: build
  script:
    - dotnet build
  except:
    - main

build_job: # Assembles the project generating jar, a zip file of the source and a zip with pmd, javadoc jacoco and junit reports
  stage: build
  script:
    - dotnet build
    - dotnet publish -c Release -o ./artifacts
  artifacts:
    paths:
      - artifacts/
  only:
    - main

test_job: # Executes testing of the project
  stage: test
  script:
    - dotnet test
