test_job:
  image: mcr.microsoft.com/dotnet/sdk:latest
  tags: 
    - LDS
  stage: test
  only:
    - main
    - dev
  script:
    - echo "Running the test job."
    - cd backend
    - dotnet test --no-restore