variables:
  GIT_SSL_NO_VERIFY: '1'

stages:
  - build
  - test
  - release
  - deploy

before_script:
  - echo "Starting CI/CD"

build_job:
  image: mcr.microsoft.com/dotnet/sdk:latest
  tags: 
    - LDS
  stage: build
  only:
    - main
  script:
    - echo "Running the build job."
    - cd backend
    - dotnet build --no-restore
    - dotnet publish -c Release -o ./artifacts
  artifacts:
    paths:
      - artifacts/

test_job:
  image: mcr.microsoft.com/dotnet/sdk:latest
  tags: 
    - LDS
  stage: test
  only:
    - main

test_job: # Executes testing of the project
  stage: test
  script:
    - dotnet test
